name: 'Coverage'

env:
  MONGODB_URI: ${{secrets.MONGODB_URI}}

on:
    pull_request:
        branches:
            - main
    push:
        branches:
            - socket-testing
jobs:
    coverage:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - run: npm run dev-build --if-present
            - uses: ArtiomTr/jest-coverage-report-action@v2