name: Deploy

on:
  push:
    branches:
      - setup

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: akhileshns/heroku-deploy@v3.13.15 # This is the action
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: "safe-bastion-28592" #Must be unique in Heroku
          heroku_email: "julia.v.wang@gmail.com"
          usedocker: true